<a href="https://colab.research.google.com/github/jminango20/Pandas/blob/master/Indexing%2C_Selecting_and_Assigning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Selecting specific values of a pandas DataFrame or Series to work on is an implicit step in almost any data operation you'll run, so one of the first things you need to learn in working with data in Python is how to go about selecting the data points relevant to you quickly and effectively.

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('/content/drive/My Drive/Colab Notebooks/Pandas/winemag-data_first150k.csv')
df.head()

   Unnamed: 0 country  ...             variety                   winery
0           0      US  ...  Cabernet Sauvignon                    Heitz
1           1   Spain  ...       Tinta de Toro  Bodega Carmen Rodríguez
2           2      US  ...     Sauvignon Blanc                 Macauley
3           3      US  ...          Pinot Noir                    Ponzi
4           4  France  ...  Provence red blend     Domaine de la Bégude

[5 rows x 11 columns]

In Python, we can access the property of an object by accessing it as an attribute. A book object, for example, might have a title property, which we can access by calling book.title. Columns in a pandas DataFrame work in much the same way.

Hence to access the country property of reviews we can use:

In [4]:
df.country

0             US
1          Spain
2             US
3             US
4         France
           ...
150925     Italy
150926    France
150927     Italy
150928    France
150929     Italy
Name: country, Length: 150930, dtype: object

If we have a Python dictionary, we can access its values using the indexing `([])` operator. We can do the same with columns in a DataFrame

In [7]:
df['country']

0             US
1          Spain
2             US
3             US
4         France
           ...
150925     Italy
150926    France
150927     Italy
150928    France
150929     Italy
Name: country, Length: 150930, dtype: object

Series we can use the indexing operator [] once more

In [8]:
df.country[4]

'France'

## Indexing in pandas

Pandas has its own accessor operators, `loc` and `iloc`

**Index-based selection**: Selecting data based on its numerical position in the data. 

To select the first row of data in a DataFrame, we may use the following:

In [9]:
df.iloc[0]

Unnamed: 0                                                     0
country                                                       US
description    This tremendous 100% varietal wine hails from ...
designation                                    Martha's Vineyard
points                                                        96
price                                                        235
province                                              California
region_1                                             Napa Valley
region_2                                                    Napa
variety                                       Cabernet Sauvignon
winery                                                     Heitz
Name: 0, dtype: object

Both `loc` and `iloc` are row-first, column-second. 

This is the opposite of what we do in native Python, which is column-first, row-second.

**To get a column with iloc, we can do the following:**

In [11]:
df.iloc[:,1]

0             US
1          Spain
2             US
3             US
4         France
           ...
150925     Italy
150926    France
150927     Italy
150928    France
150929     Italy
Name: country, Length: 150930, dtype: object

On its own, the `:` operator, means "everything". 

When combined with other selectors, however, it can be used to indicate a range of values. For example, to select the country column from just the first, second, and third row, we would do:

In [14]:
df.iloc[:3,1]

0       US
1    Spain
2       US
Name: country, dtype: object

In [15]:
#Or, to select just the second and third entries, we would do:
df.iloc[1:3,1]

1    Spain
2       US
Name: country, dtype: object

In [17]:
#It's also possible to pass a list:
df.iloc[[1,2,3,4],1]

1     Spain
2        US
3        US
4    France
Name: country, dtype: object

Finally, it's worth knowing that negative numbers can be used in selection. This will start counting forwards from the end of the values. So for example here are the last five elements of the dataset.

In [19]:
df.iloc[-5:]

        Unnamed: 0 country  ...          variety                 winery
150925      150925   Italy  ...      White Blend  Feudi di San Gregorio
150926      150926  France  ...  Champagne Blend              H.Germain
150927      150927   Italy  ...      White Blend              Terredora
150928      150928  France  ...  Champagne Blend                 Gosset
150929      150929   Italy  ...     Pinot Grigio          Alois Lageder

[5 rows x 11 columns]

## Label-based selection

The second paradigm for attribute selection is the one followed by the `loc` operator: label-based selection. In this paradigm, it's the data index value, not its position, which matters.

For example, to get the first entry in df, we would now do the following:

In [20]:
df.loc[0,'country']

'US'

In [21]:
df.loc[:,['country','description','price','province']]

       country  ...            province
0           US  ...          California
1        Spain  ...      Northern Spain
2           US  ...          California
3           US  ...              Oregon
4       France  ...            Provence
...        ...  ...                 ...
150925   Italy  ...      Southern Italy
150926  France  ...           Champagne
150927   Italy  ...      Southern Italy
150928  France  ...           Champagne
150929   Italy  ...  Northeastern Italy

[150930 rows x 4 columns]

## Manipulating the index
Label-based selection derives its power from the labels in the index. Critically, the index we use is not immutable. We can manipulate the index in any way we see fit.

The set_index() method can be used to do the job. Here is what happens when we set_index to the title field:

In [23]:
df.columns

Index(['Unnamed: 0', 'country', 'description', 'designation', 'points',
       'price', 'province', 'region_1', 'region_2', 'variety', 'winery'],
      dtype='object')

In [24]:
df.set_index('Unnamed: 0')

           country  ...                   winery
Unnamed: 0          ...
0               US  ...                    Heitz
1            Spain  ...  Bodega Carmen Rodríguez
2               US  ...                 Macauley
3               US  ...                    Ponzi
4           France  ...     Domaine de la Bégude
...            ...  ...                      ...
150925       Italy  ...    Feudi di San Gregorio
150926      France  ...                H.Germain
150927       Italy  ...                Terredora
150928      France  ...                   Gosset
150929       Italy  ...            Alois Lageder

[150930 rows x 10 columns]

## Conditional selection
So far we've been indexing various strides of data, using structural properties of the DataFrame itself. To do interesting things with the data, however, we often need to ask questions based on conditions.

In [25]:
df.country == 'Italy'

0         False
1         False
2         False
3         False
4         False
          ...
150925     True
150926    False
150927     True
150928    False
150929     True
Name: country, Length: 150930, dtype: bool

This operation produced a Series of `True/False` booleans based on the country of each record. This result can then be used inside of `loc` to select the relevant data:

In [27]:
df.loc[df.country=='Italy']

        Unnamed: 0 country  ...          variety                 winery
10              10   Italy  ...         Friulano       Borgo del Tiglio
32              32   Italy  ...       Sangiovese        Abbadia Ardenga
35              35   Italy  ...       Sangiovese               Carillon
37              37   Italy  ...       Sangiovese             Avignonesi
38              38   Italy  ...       Sangiovese       Casina di Cornia
...            ...     ...  ...              ...                    ...
150920      150920   Italy  ...  Champagne Blend                Letrari
150922      150922   Italy  ...            Tocai      Ronchi di Manzano
150925      150925   Italy  ...      White Blend  Feudi di San Gregorio
150927      150927   Italy  ...      White Blend              Terredora
150929      150929   Italy  ...     Pinot Grigio          Alois Lageder

[23478 rows x 11 columns]

We also wanted to know which ones are better than average. Wines are reviewed on a 80-to-100 point scale, so this could mean wines that accrued at least 90 points.

We can use the ampersand (`&`) to bring the two questions together:

In [29]:
df.loc[(df.country=='Italy') & (df.points >= 90)]

        Unnamed: 0 country  ...          variety                 winery
10              10   Italy  ...         Friulano       Borgo del Tiglio
32              32   Italy  ...       Sangiovese        Abbadia Ardenga
35              35   Italy  ...       Sangiovese               Carillon
37              37   Italy  ...       Sangiovese             Avignonesi
38              38   Italy  ...       Sangiovese       Casina di Cornia
...            ...     ...  ...              ...                    ...
150920      150920   Italy  ...  Champagne Blend                Letrari
150922      150922   Italy  ...            Tocai      Ronchi di Manzano
150925      150925   Italy  ...      White Blend  Feudi di San Gregorio
150927      150927   Italy  ...      White Blend              Terredora
150929      150929   Italy  ...     Pinot Grigio          Alois Lageder

[7945 rows x 11 columns]

Pandas comes with a few built-in conditional selectors, two of which we will highlight here.

The first is isin. isin is lets you select data whose value `"is in"` a list of values. For example, here's how we can use it to select wines only from Italy or France:

In [31]:
df.loc[df.country.isin(['Italy','France'])]

        Unnamed: 0 country  ...             variety                 winery
4                4  France  ...  Provence red blend   Domaine de la Bégude
10              10   Italy  ...            Friulano       Borgo del Tiglio
13              13  France  ...              Tannat      Vignobles Brumont
18              18  France  ...              Malbec     Château Lagrézette
32              32   Italy  ...          Sangiovese        Abbadia Ardenga
...            ...     ...  ...                 ...                    ...
150925      150925   Italy  ...         White Blend  Feudi di San Gregorio
150926      150926  France  ...     Champagne Blend              H.Germain
150927      150927   Italy  ...         White Blend              Terredora
150928      150928  France  ...     Champagne Blend                 Gosset
150929      150929   Italy  ...        Pinot Grigio          Alois Lageder

[44576 rows x 11 columns]

The second is `isnull` (and its companion `notnull`). These methods let you highlight values which are (or are not) empty (`NaN`). For example, to filter out wines lacking a price tag in the dataset, here's what we would do:

In [32]:
df.loc[df.price.isnull()]

        Unnamed: 0      country  ...          variety             winery
32              32        Italy  ...       Sangiovese    Abbadia Ardenga
56              56       France  ...  Sauvignon Blanc   Domaine Vacheron
72              72        Italy  ...         Nebbiolo    Silvano Bolmida
82              82        Italy  ...         Nebbiolo              Ceste
116            116        Spain  ...       Monastrell  Casa de la Ermita
...            ...          ...  ...              ...                ...
150377      150377  New Zealand  ...            Syrah       Matua Valley
150378      150378  New Zealand  ...            Syrah             Kusuda
150587      150587       Canada  ...         Riesling              Colio
150673      150673           US  ...        Zinfandel        Taft Street
150922      150922        Italy  ...            Tocai  Ronchi di Manzano

[13695 rows x 11 columns]

In [33]:
df.loc[df.price.notnull()]

        Unnamed: 0 country  ...             variety                   winery
0                0      US  ...  Cabernet Sauvignon                    Heitz
1                1   Spain  ...       Tinta de Toro  Bodega Carmen Rodríguez
2                2      US  ...     Sauvignon Blanc                 Macauley
3                3      US  ...          Pinot Noir                    Ponzi
4                4  France  ...  Provence red blend     Domaine de la Bégude
...            ...     ...  ...                 ...                      ...
150925      150925   Italy  ...         White Blend    Feudi di San Gregorio
150926      150926  France  ...     Champagne Blend                H.Germain
150927      150927   Italy  ...         White Blend                Terredora
150928      150928  France  ...     Champagne Blend                   Gosset
150929      150929   Italy  ...        Pinot Grigio            Alois Lageder

[137235 rows x 11 columns]

## Assigning data
Going the other way, assigning data to a DataFrame is easy. You can assign either a constant value:

In [34]:
df.columns

Index(['Unnamed: 0', 'country', 'description', 'designation', 'points',
       'price', 'province', 'region_1', 'region_2', 'variety', 'winery'],
      dtype='object')

In [35]:
df.designation = 'everyone'

In [36]:
df.head(10)

   Unnamed: 0 country  ...             variety                   winery
0           0      US  ...  Cabernet Sauvignon                    Heitz
1           1   Spain  ...       Tinta de Toro  Bodega Carmen Rodríguez
2           2      US  ...     Sauvignon Blanc                 Macauley
3           3      US  ...          Pinot Noir                    Ponzi
4           4  France  ...  Provence red blend     Domaine de la Bégude
5           5   Spain  ...       Tinta de Toro                Numanthia
6           6   Spain  ...       Tinta de Toro                 Maurodos
7           7   Spain  ...       Tinta de Toro  Bodega Carmen Rodríguez
8           8      US  ...          Pinot Noir                Bergström
9           9      US  ...          Pinot Noir                Blue Farm

[10 rows x 11 columns]

Or with an iterable of values:

In [39]:
df.points = range(len(df),0,-1)

In [40]:
df.head(10)

   Unnamed: 0 country  ...             variety                   winery
0           0      US  ...  Cabernet Sauvignon                    Heitz
1           1   Spain  ...       Tinta de Toro  Bodega Carmen Rodríguez
2           2      US  ...     Sauvignon Blanc                 Macauley
3           3      US  ...          Pinot Noir                    Ponzi
4           4  France  ...  Provence red blend     Domaine de la Bégude
5           5   Spain  ...       Tinta de Toro                Numanthia
6           6   Spain  ...       Tinta de Toro                 Maurodos
7           7   Spain  ...       Tinta de Toro  Bodega Carmen Rodríguez
8           8      US  ...          Pinot Noir                Bergström
9           9      US  ...          Pinot Noir                Blue Farm

[10 rows x 11 columns]

In [44]:
df = pd.read_csv('/content/drive/My Drive/Colab Notebooks/Pandas/winemag-data_first150k.csv',index_col=0)
df.head()

  country  ...                   winery
0      US  ...                    Heitz
1   Spain  ...  Bodega Carmen Rodríguez
2      US  ...                 Macauley
3      US  ...                    Ponzi
4  France  ...     Domaine de la Bégude

[5 rows x 10 columns]